require("core.settings")
require("core.autocmds")
require("core.neovide")

require("plugins.lazy")
require("plugins.config.webdevicons")
require("plugins.config.lualine")
require("plugins.config.neotree")
require("plugins.config.treesitter")
require("plugins.config.window-picker")
require("plugins.config.gitsigns")
require("plugins.config.telescope")
require("plugins.config.colorizer")
require("plugins.config.autopairs")
require("plugins.config.autotag")
require("plugins.config.chatgpt")
require("plugins.config.local-highlight")
require("plugins.config.toggleterm")
require("plugins.config.indent-blankline")
require("plugins.config.lsp.mason")
require("plugins.config.lsp.lspzero")
require("plugins.config.nvim-ufo")
require("plugins.config.startup")

require("core.colorscheme")
require("core.keymaps")
