require("core.settings")
require("core.keymaps")
require("core.autocmds")

require("plugins.lazy")
require("plugins.config.dracula")
require("plugins.config.webdevicons")
require("plugins.config.lualine")
require("plugins.config.neotree")
require("plugins.config.treesitter")
require("plugins.config.window-picker")
require("plugins.config.gitsigns")
require("plugins.config.move-nvim")
require("plugins.config.telescope")
require("plugins.config.colorizer")
require("plugins.config.autopairs")
require("plugins.config.cmp")
require("plugins.config.chatgpt")
require("plugins.config.local-highlight")
require("plugins.config.diffview")
require("plugins.config.hbac")
require("plugins.config.vim-daadbod")

require("plugins.config.lsp.mason")
require("plugins.config.lsp.lspsaga")
require("plugins.config.lsp.lspconfig")
require("plugins.config.lsp.null-ls")

