local v = vim.opt

v.guifont = "CaskaydiaCove NFM:h10"
v.showmode = false
v.showcmd = true
v.cursorline = true
v.title = true
v.titlestring = ""
v.syntax = "on"
v.number = true
v.relativenumber = true
v.termguicolors = true
v.signcolumn = "yes"
v.cmdheight = 1
vim.g.icons_enabled = true
vim.o.fillchars = [[vert:█,eob: ,fold: ,foldopen:,foldsep: ,foldclose:]]
v.wildmenu = true
v.backup = false
v.swapfile = false
v.writebackup = false
v.history = 50
v.undolevels = 1000
v.updatetime = 500
v.copyindent = true
v.autowrite = true
v.autoread = true
v.incsearch = true
v.ignorecase = true
v.smartcase = true
v.wrap = false
v.scrolloff = 5
v.completeopt = "menu,menuone,noselect"
v.encoding = "utf-8"
v.fileencoding = "utf-8"
vim.scriptencoding = "utf-8"
vim.termeconfing = "utf-8"
v.autoindent = true
v.expandtab = true
v.tabstop = 4
v.softtabstop = 4
v.shiftwidth = 4
v.backspace = "indent,eol,start"
v.smarttab = true
